import { corsHeaders } from '../_shared/cors.ts';

interface RequestBody {
  imageUrl: string;
}

interface ChecklistItem {
  id: string;
  task: string;
  category: string;
  priority: 'high' | 'medium' | 'low';
  completed: boolean;
  estimatedTime: string;
  reason?: string;
}

Deno.serve(async (req: Request) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    const { imageUrl }: RequestBody = await req.json();

    if (!imageUrl) {
      return new Response(
        JSON.stringify({ error: 'Image URL is required' }),
        {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Simulate AI analysis with realistic data
    const roomDescription = "A cluttered living room with potential for minimalist transformation. The space has good natural light and basic furniture that can be optimized for a cleaner, more peaceful environment.";
    
    const imagePrompt = "A minimalist living room with clean lines, neutral colors, organized storage, and plenty of open space. Natural light fills the room, highlighting carefully selected furniture and decor items.";

    // Generate a placeholder transformed image URL (in production, this would be generated by AI)
    const transformedImageUrl = "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800";

    // Generate personalized checklist based on common minimalist principles
    const checklist: ChecklistItem[] = [
      {
        id: '1',
        task: 'Remove unnecessary items from surfaces',
        category: 'Decluttering',
        priority: 'high',
        completed: false,
        estimatedTime: '30 minutes',
        reason: 'Clear surfaces create visual calm and make the space feel larger'
      },
      {
        id: '2',
        task: 'Organize books and media into designated storage',
        category: 'Organization',
        priority: 'medium',
        completed: false,
        estimatedTime: '45 minutes',
        reason: 'Hidden storage maintains clean lines while keeping items accessible'
      },
      {
        id: '3',
        task: 'Choose one focal point for the room',
        category: 'Styling',
        priority: 'high',
        completed: false,
        estimatedTime: '15 minutes',
        reason: 'A single focal point prevents visual overwhelm and creates intentional design'
      },
      {
        id: '4',
        task: 'Remove excess throw pillows and blankets',
        category: 'Decluttering',
        priority: 'medium',
        completed: false,
        estimatedTime: '10 minutes',
        reason: 'Fewer accessories create a cleaner, more sophisticated look'
      },
      {
        id: '5',
        task: 'Create designated homes for daily items',
        category: 'Organization',
        priority: 'high',
        completed: false,
        estimatedTime: '60 minutes',
        reason: 'Everything having a place prevents future clutter accumulation'
      },
      {
        id: '6',
        task: 'Add one natural element (plant or natural material)',
        category: 'Styling',
        priority: 'low',
        completed: false,
        estimatedTime: '20 minutes',
        reason: 'Natural elements add warmth and life to minimalist spaces'
      }
    ];

    const response = {
      transformedImageUrl,
      checklist,
      roomDescription,
      imagePrompt,
      success: true
    };

    return new Response(
      JSON.stringify(response),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error) {
    console.error('Error in ai-room-transform function:', error);
    
    return new Response(
      JSON.stringify({ 
        error: 'Internal server error',
        details: error instanceof Error ? error.message : 'Unknown error'
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});